spring:
  profiles:
    active: stage
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${gabia.mysql.hostname}/oauth2provider?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${gabia.mysql.username}
    password: ${gabia.mysql.password}
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: ${gabia.redis.hostname}
    port: 5000
    password: ${gabia.redis.password}
  thymeleaf: cache=false
logging:
  level:
    com:
      gabia: info
    org:
      springframework:
        jdbc:
          core: off