apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:  
    {{- if .Values.affinity }}
      affinity:
    {{- toYaml .Values.affinity | nindent 8 }}
    {{- end }}
    {{- with .Values.mount }}
      volumes: 
      {{- range . }}
        {{- if eq .type "hostPath" }}
        - name: {{ .name }}
          hostPath:
            path: {{ .path }}
        {{- end }}
        {{- if eq .type "persistVolume" }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- with .Values.hosts }}
      hostAliases: 
      {{- range . }}
      - ip: {{ .ip }}
        hostnames:
          {{- toYaml .hostnames | nindent 10 }}
      {{- end }}
    {{- end }}
      containers:
      - name: {{ include "app.name" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
      {{- with .Values.mount }}
        volumeMounts: 
        {{- range . }}
          - name: {{ .name }}
            mountPath: {{ .path}}
        {{- end }}
      {{- end }}
      {{- if .Values.readinessProbe }}
        readinessProbe:
        {{- toYaml .Values.readinessProbe | nindent 10 }}
      {{- end }}
      {{- if .Values.startupProbe }}
        startupProbe:
        {{- toYaml .Values.startupProbe | nindent 10 }}
      {{- end }}
      {{- if .Values.livenessProbe }}
        livenessProbe:
        {{- toYaml .Values.livenessProbe | nindent 10 }}
      {{- end }}
      {{- if .Values.lifecycle }}
        lifecycle:
        {{- toYaml .Values.lifecycle | nindent 10 }}
      {{- end }}       
      {{- if .Values.resources }}
        resources:
        {{ toYaml .Values.resources | nindent 10 }}
      {{- end }}
    {{- with .Values.addImage }}
      {{- range . }}
      - name: {{ .name }}
        image: {{ .respository }}:{{ .tag }}
        imagePullPolicy: {{ .pullPolicy }}
        ports:
        - containerPort: {{ .port }}
      {{- end }}
    {{- end }}