# gradle 빌드
gradle-build-prod:
  extends: .gradle-build
  only:
    - /^v(\d+).(\d+).(\d+)$/
  except:
    - branches
  tags:
    - prod
    - gabia

# docker 빌드
docker-build-prod:
  extends: .docker-build
  variables:
    BUILD_TYPE: ${PRODUCTION}
    IMAGE_TAG: ${CI_COMMIT_TAG}
    # GKMS_ROLE_ID: ${PROD_KMS_ROLE_ID}
    # GKMS_SECRET_ID: ${PROD_KMS_ROLE_SECRET}
    # GKMS_ENGINE_NAME: ${PROD_KMS_HIWORKS_ENGINE}
    # GKMS_URL: ${KMS_ENDPOINT}
  only:
    - /^v(\d+).(\d+).(\d+)$/
  except:
    - branches
  tags:
    - prod
    - gabia

# 배포
deploy-prod:
  extends: .deploy
  variables:
    BUILD_TYPE: ${PRODUCTION}
    CLUSTER_TYPE: ${KUBE_CLUSTER_PROD}
    IMAGE_TAG: ${CI_COMMIT_TAG}
    HOST_URL: auth-api.gabia.com
    LB_IP: ${PROD_LB_IP_OFFICE}
    HELM_CHART_NAME: ${HELM_CHART_DEFAULT_NAME}-${PRODUCTION}
  environment:
    name: production
  when: manual
  only:
    - /^v(\d+).(\d+).(\d+)$/
  except:
    - branches
  tags:
    - prod
    - gabia
